import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { buildStructuredEvidence, mergeMappedFields, suggestFieldsFromEvidence, usefulLocalFields } from "../src/utils/templateEvidence.js";
const source = async (file) => readFile(new URL(file, import.meta.url), "utf8");

test("Super Admin and consultant can create templates while clients cannot", async () => { const app = await source("../src/App.jsx"); assert.match(app, /\[1, 2\]\.includes\(getRoleId\(\)\)/); assert.match(app, /Clients cannot access Templates/); });
test("consultant sees NexaPort Provided and My Templates", async () => { const text = await source("../src/pages/TemplatesPage.jsx"); assert.match(text, /NexaPort Provided/); assert.match(text, /My Templates/); });
test("template permissions still control edit use and duplication", async () => { const text = await source("../src/pages/TemplatesPage.jsx"); assert.match(text, /permissions\.canEdit/); assert.match(text, /permissions\.canUse/); assert.match(text, /Duplicate to My Templates/); });
test("selecting a PDF or XML cannot call a source upload endpoint", async () => { const api = await source("../src/api/templateApi.js"); const editor = await source("../src/pages/TemplateEditorPage.jsx"); assert.doesNotMatch(api + editor, /templates\/upload-url|createTemplateUploadUrl|uploadTemplateSource/); });
test("source file is not sent to a backend extraction endpoint", async () => { const api = await source("../src/api/templateApi.js"); assert.doesNotMatch(api, /\/extract|FormData|axios\.put/); });
test("AcroForm fields are extracted locally with page coordinates", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /getAnnotations\(\)/); assert.match(text, /sourceCoordinates/); assert.match(text, /sourcePageNumber/); });
test("text PDF extraction happens locally", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /getTextContent\(\)/); assert.match(text, /suggestFieldsFromText/); assert.match(text, /labels? require review|suggestions require review/i); });
test("scanned PDFs start local OCR", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /import\("tesseract\.js"\)/); assert.match(text, /worker\.recognize\(canvas\)/); });
test("OCR worker terminates after completion", async () => assert.match(await source("../src/utils/templateSourceExtraction.js"), /finally[\s\S]*worker\?\.terminate\(\)/));
test("OCR can be cancelled", async () => { const editor = await source("../src/pages/TemplateEditorPage.jsx"); const utility = await source("../src/utils/templateSourceExtraction.js"); assert.match(editor, /AbortController/); assert.match(editor, /> Cancel</); assert.match(utility, /signal\?\.aborted/); });
test("OCR has page and source-size limits", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /ocrPages: 10/); assert.match(text, /pdfBytes: 10 \* 1024 \* 1024/); });
test("local extraction shows required progress stages", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); for (const stage of ["Preparing document", "Reading page", "Detecting text", "Building field suggestions"]) assert.match(text, new RegExp(stage)); });
test("XML is parsed locally", async () => assert.match(await source("../src/utils/templateSourceExtraction.js"), /new DOMParser\(\)/));
test("unsafe XML is rejected", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /DOCTYPE\|<!ENTITY/); assert.match(text, /unsafe declarations or processing instructions/); });
test("only normalized fields and metadata are sent when saving", async () => { const text = await source("../src/pages/TemplateEditorPage.jsx"); const call = text.match(/createTemplate\(\{[^}]+\}\)/)?.[0] || ""; assert.equal(call, "createTemplate({ title, description, sourceType: effectiveSourceType, extractionMethod: effectiveExtractionMode, fields, layout })"); });
test("template source bytes are never put in web storage", async () => { const text = await source("../src/pages/TemplateEditorPage.jsx") + await source("../src/utils/templateSourceExtraction.js"); assert.doesNotMatch(text, /localStorage|sessionStorage|indexedDB/i); });
test("no temporary object URLs are created", async () => assert.doesNotMatch(await source("../src/utils/templateSourceExtraction.js"), /createObjectURL/));
test("file and PDF resources are released after processing", async () => { const editor = await source("../src/pages/TemplateEditorPage.jsx"); const utility = await source("../src/utils/templateSourceExtraction.js"); assert.match(editor, /finally[\s\S]*discardFile\(\)/); assert.match(utility, /loadingTask\.destroy/); assert.match(utility, /pdfDocument\.cleanup/); });
test("workers are cleaned up when the page closes", async () => assert.match(await source("../src/pages/TemplateEditorPage.jsx"), /useEffect\(\(\) => \(\) => \{ extractionController\.current\?\.abort\(\); ocrWorker\.current\?\.terminate\(\); \}, \[\]\)/));
test("extraction errors never use upload wording", async () => { const editor = await source("../src/pages/TemplateEditorPage.jsx"); assert.doesNotMatch(editor, /Unable to upload template source|Field extraction failed/); assert.match(editor, /Unable to read fields from this PDF|Unable to parse this XML file/); });
test("field editor remains functional", async () => { const text = await source("../src/components/templates/FieldEditor.jsx"); for (const token of ["Add field", "Remove", "Move"]) assert.match(text, new RegExp(token, "i")); });
test("photo-field configuration remains functional", async () => assert.match(await source("../src/components/templates/FieldEditor.jsx"), /Include photo fields/));
test("report images remain browser-local until PDF generation", async () => { const cache = await source("../src/utils/reportMediaCache.js"); const api = await source("../src/api/reportApi.js"); assert.match(cache, /indexedDB\.open/); assert.match(cache, /readAsDataURL/); assert.doesNotMatch(api, /photo-upload-url|registerReportPhoto|axios\.put/); assert.match(api, /application\/vnd\.nexaport\.report\+json/); });
test("photo and signature controls use the local report media cache", async () => { const detail = await source("../src/pages/ReportDetailPage.jsx"); assert.match(detail, /cacheReportMedia/); assert.match(detail, /Choose signature image/); assert.match(detail, /clearReportMedia/); assert.doesNotMatch(detail, /createPhotoUploadUrl|registerReportPhoto|uploadReportPhoto/); });
test("generated report preview and download remain wired", async () => { const detail = await source("../src/pages/ReportDetailPage.jsx"); const preview = await source("../src/components/templates/ReportPreview.jsx"); assert.match(detail, /generateReport/); assert.match(preview, /Preview PDF/); assert.match(preview, /Download PDF/); });
test("unrelated directory routes remain intact", async () => { const app = await source("../src/App.jsx"); for (const route of ["/requests", "/fleet", "/ports", "/experts"]) assert.match(app, new RegExp(`path="${route}"`)); });

// --- Bug fix verification tests ---

test("PDF extraction does not call a missing destroy method on PDFDocumentProxy", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.doesNotMatch(text, /await pdf\?\.destroy\(\)/); assert.doesNotMatch(text, /\bpdf\.destroy\(\)/); });
test("PDFDocument cleanup is called only when supported", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /typeof pdfDocument\?\.cleanup === "function"/); });
test("loading task destroy is called only when supported", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /typeof loadingTask\?\.destroy === "function"/); });
test("successful extraction returns before cleanup without cleanup changing its value", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /return \{ mode: "text", fields:/); assert.match(text, /finally \{ try/); });
test("cleanup failure does not discard extracted fields", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /catch \(cleanupError\)/); assert.match(text, /console\.warn.*PDF resource cleanup/); });
test("actual parsing failure displays a user-friendly message", async () => { const text = await source("../src/pages/TemplateEditorPage.jsx"); assert.match(text, /Unable to read fields from this PDF\. You can add fields manually\./); });
test("OCR starts only after positional text is not meaningful", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /if \(meaningful >= 20\) return/); assert.match(text, /return await recognizeScannedPdf/); });
test("PDF worker is terminated after processing via loadingTask.destroy", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /finally[\s\S]*loadingTask\?\.destroy/); });
test("Required checkbox and label share one label element", async () => { const text = await source("../src/components/templates/FieldEditor.jsx"); assert.match(text, /<label className="template-field-checkbox"><input/); assert.match(text, /Required<\/span><\/label>/); });
test("Required checkbox text appears beside the checkbox via inline-flex", async () => { const css = await source("../src/styles/templates.css"); assert.match(css, /\.template-field-checkbox\{display:inline-flex/); });
test("clicking the Required text toggles the checkbox because they share a label", async () => { const text = await source("../src/components/templates/FieldEditor.jsx"); const labelMatch = text.match(/<label className="template-field-checkbox">[\s\S]*?<\/label>/); assert.ok(labelMatch, "Expected a label with class template-field-checkbox"); assert.match(labelMatch[0], /type="checkbox"/); assert.match(labelMatch[0], /Required/); });
test("Required checkbox remains keyboard accessible via native input", async () => { const text = await source("../src/components/templates/FieldEditor.jsx"); assert.match(text, /type="checkbox".*checked=\{field\.required\}/); });
test("mobile field layout does not separate the checkbox and label", async () => { const css = await source("../src/styles/templates.css"); assert.doesNotMatch(css, /\.template-field-checkbox[^{]*\{[^}]*display:\s*grid/); assert.doesNotMatch(css, /\.template-field-checkbox[^{]*\{[^}]*display:\s*block/); });
test("add field remains functional", async () => { const text = await source("../src/components/templates/FieldEditor.jsx"); assert.match(text, /onClick=\{\(\) => add\(\)\}/); assert.match(text, /Add field/); });
test("extracted fields remain editable", async () => { const text = await source("../src/components/templates/FieldEditor.jsx"); assert.match(text, /onChange=\{\(event\) => update\(index/); assert.match(text, /disabled=\{readOnly\}/); });
test("photo-field option remains unchanged", async () => { const text = await source("../src/components/templates/FieldEditor.jsx"); assert.match(text, /Include photo fields/); assert.match(text, /captionEnabled/); });
test("file selection never calls AI mapping", async () => { const text = await source("../src/pages/TemplateEditorPage.jsx"); const choose = text.match(/const chooseFile[\s\S]*?; \};/)?.[0] || ""; assert.doesNotMatch(choose, /mapTemplateFields/); });
test("AI mapping is a single explicit document-level call", async () => { const text = await source("../src/pages/TemplateEditorPage.jsx"); assert.match(text, /Map fields with AI/); const handler = text.match(/const mapWithAi[\s\S]*?\n  \};/)?.[0] || ""; assert.equal((handler.match(/mapTemplateFields\(/g) || []).length, 1); });
test("complete AcroForm extraction does not offer AI mapping", async () => { const utility = await source("../src/utils/templateSourceExtraction.js"); const editor = await source("../src/pages/TemplateEditorPage.jsx"); assert.match(utility, /mode: "acroform"[\s\S]*?aiMappingRecommended: false/); assert.match(editor, /result\.aiMappingRecommended \?/); });
test("only normalized evidence is submitted to AI", async () => { const text = await source("../src/pages/TemplateEditorPage.jsx"); assert.match(text, /mapTemplateFields\(mappingEvidence\)/); assert.match(text, /pagesOrSheets: result\.evidence\.pagesOrSheets/); assert.doesNotMatch(text, /mapTemplateFields\(file\)|FormData/); });
test("mapped fields remain editable", async () => { const editor = await source("../src/pages/TemplateEditorPage.jsx"); const fields = await source("../src/components/templates/FieldEditor.jsx"); assert.match(editor, /mergeMappedFields/); assert.match(fields, /onChange=\{\(event\) => update\(index/); });
test("AI failure keeps only useful local suggestions", async () => { const text = await source("../src/pages/TemplateEditorPage.jsx"); const handler = text.match(/const mapWithAi[\s\S]*?\n  \};/)?.[0] || ""; const catchBody = handler.match(/catch \(requestError\)[\s\S]*?finally/)?.[0] || ""; assert.match(catchBody, /usefulLocalFields/); assert.match(catchBody, /Field mapping is temporarily unavailable\. You can retry or edit the local suggestions\./); });
test("DOCX and XLSX are parsed locally", async () => { const text = await source("../src/utils/templateSourceExtraction.js"); assert.match(text, /mammoth\.convertToHtml/); assert.match(text, /JSZip\.loadAsync/); assert.match(text, /xlsxSheets: 10/); });

const section = (title) => ({ text: title, bold: true, fontSize: 16 });
const marinaPages = buildStructuredEvidence([{ name: "Page 1", lines: [
  { text: "Marina Dock Safety Inspection Checklist" }, { text: "POPProbe" }, { text: "popprobe.com" }, section("Inspection Information"),
  { text: "Marina Name *" }, { text: "Dock/Pier Number *" }, { text: "Date *" }, { text: "____ / ____ / ____" }, { text: "Inspector Name *" },
  section("Dock Structure"), { text: "Decking in good condition? *" }, { text: "Yes" }, { text: "No" }, { text: "Handrails secure? * Yes No" }, { text: "Cleats secure? * Yes No" }, { text: "Pilings sound? * Yes No" },
  section("Electrical"), { text: "Shore power outlets safe? * Yes No" }, { text: "Ground fault protection working? * Yes No" }, { text: "Cables protected? * Yes No" },
  section("Fire Safety"), { text: "Fire extinguishers accessible? * Yes No" }, { text: "Fire hose serviceable? * Yes No" }, { text: "Emergency access clear? * Yes No" },
  section("Safety Assessment"), { text: "Trip hazards controlled? * Yes No" }, { text: "Life rings available? * Yes No" }, { text: "Ladders secure? * Yes No" },
] }, { name: "Page 2", lines: [
  { text: "Marina Dock Safety Inspection Checklist" }, section("Equipment Verification"), { text: "Dock cart serviceable? * Yes No" }, { text: "Emergency lighting works? * Yes No" }, { text: "First aid kit stocked? * Yes No" },
  section("Environmental & Housekeeping"), { text: "Waste contained? * Yes No" }, { text: "Waterway free of debris? * Yes No" }, { text: "Spill kit available? * Yes No" },
  section("Compliance Verification"), { text: "Permits displayed? * Yes No" }, { text: "Required signage posted? * Yes No" },
  section("Communication & Prevention"), { text: "Emergency contacts posted? * Yes No" }, { text: "Preventive maintenance current? * Yes No" },
  section("Summary & Sign-Off"), { text: "Overall dock condition? * Good Fair Poor" }, { text: "Inspector Comments *" }, { text: "Inspector Signature *" }, { text: "Download" }, { text: "2" },
] }]);

const uscgPages = buildStructuredEvidence([{ name: "Page 1", lines: [
  { text: "USCG Vessel Inspection Checklist" }, { text: "Capterra rating ★★★★★" }, section("Structural Integrity"), { text: "Hull condition" }, { text: "Good Fair Poor" }, { text: "Deck condition Good Fair Poor" }, { text: "Superstructure condition Good Fair Poor" }, { text: "Stability and freeboard" }, { text: "Acceptable Unacceptable" },
  section("Safety Protocols"), { text: "Life jackets available and functional" }, { text: "Yes No" }, { text: "Fire extinguishers serviced and charged Yes No" }, { text: "Safety signage and markings clear Yes No" },
] }, { name: "Page 2", lines: [section("Emergency Equipment"), { text: "EPIRB tested Yes No" }, { text: "Flares and signals in date and functional Yes No" }, { text: "Dewatering pumps and bilge alarms operational Yes No" }, { text: "Register using this QR code" }, { text: "Automatic reports advertisement" }, { text: "Legal disclaimer" }]}]);

test("Marina fixture yields ten sections and thirty meaningful fields", () => { const fields = suggestFieldsFromEvidence(marinaPages); assert.equal(new Set(fields.map((field) => field.section)).size, 10); assert.equal(fields.length, 30); assert.deepEqual(fields.find((field) => field.label === "Date"), { ...fields.find((field) => field.label === "Date"), type: "date", required: true }); assert.equal(fields.find((field) => field.label === "Decking in good condition?").type, "yes_no"); assert.equal(fields.find((field) => field.label === "Inspector Signature").type, "signature"); });
test("USCG fixture yields three sections and ten grouped fields", () => { const fields = suggestFieldsFromEvidence(uscgPages); assert.equal(new Set(fields.map((field) => field.section)).size, 3); assert.equal(fields.length, 10); assert.deepEqual(fields.find((field) => field.label === "Hull condition").options, ["Good", "Fair", "Poor"]); assert.equal(fields.find((field) => field.label === "EPIRB tested").type, "yes_no"); });
test("placeholders, isolated options and marketing are removed from evidence", () => { const text = marinaPages.flatMap((page) => page.lines.map((line) => line.text)).join("\n"); assert.doesNotMatch(text, /____|POPProbe|popprobe\.com|^Yes$|^No$|Download/m); });
test("asterisk marks required without remaining in visible labels", () => { const fields = suggestFieldsFromEvidence(marinaPages); const marina = fields.find((field) => field.label === "Marina Name"); assert.equal(marina.required, true); assert.doesNotMatch(marina.label, /\*/); });
test("AI results replace untouched suggestions while preserving manual fields", () => { const baseline = [{ fieldKey: "junk_1", label: "Date", type: "date", section: "General", suggested: true }]; const manual = { ...baseline[0], label: "Survey Date" }; const mapped = [{ fieldKey: "date", label: "Date", fieldType: "date", required: true, sectionKey: "info", sortOrder: 1, options: [] }]; const result = mergeMappedFields([manual], baseline, mapped, new Map([["info", "Inspection Information"]])); assert.equal(result.length, 2); assert.equal(result.find((field) => field.fieldKey === "junk_1").label, "Survey Date"); assert.equal(result.find((field) => field.fieldKey === "date").section, "Inspection Information"); });
test("junk fields are not restored after mapping failure", () => assert.deepEqual(usefulLocalFields([{ label: "____", suggested: true }, { label: "Inspector Name", suggested: true }]).map((field) => field.label), ["Inspector Name"]));
