export const NATIONALITIES = [
  "Afghan", "Albanian", "Algerian", "American", "Andorran", "Angolan", "Argentine", "Armenian",
  "Australian", "Austrian", "Bangladeshi", "Belgian", "Brazilian", "British", "Bulgarian", "Canadian",
  "Chilean", "Chinese", "Colombian", "Croatian", "Czech", "Danish", "Dutch", "Egyptian", "Emirati",
  "Estonian", "Finnish", "French", "German", "Ghanaian", "Greek", "Hungarian", "Icelandic", "Indian",
  "Indonesian", "Iranian", "Irish", "Israeli", "Italian", "Japanese", "Kenyan", "Korean", "Latvian",
  "Lithuanian", "Luxembourgish", "Malaysian", "Mexican", "Moroccan", "Nepalese", "New Zealander",
  "Nigerian", "Norwegian", "Pakistani", "Peruvian", "Philippine", "Polish", "Portuguese", "Qatari",
  "Romanian", "Russian", "Saudi", "Singaporean", "Slovak", "Slovenian", "South African", "Spanish",
  "Sri Lankan", "Swedish", "Swiss", "Thai", "Turkish", "Ukrainian", "Vietnamese", "Welsh", "Zimbabwean",
];

export const COUNTRIES = [
  "Please Select", "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Argentina", "Armenia",
  "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Belgium", "Brazil",
  "Bulgaria", "Canada", "Chile", "China", "Colombia", "Croatia", "Cyprus", "Czech Republic",
  "Denmark", "Egypt", "Estonia", "Finland", "France", "Germany", "Ghana", "Greece", "Hong Kong",
  "Hungary", "Iceland", "India", "Indonesia", "Ireland", "Italy", "Japan", "Kenya", "Latvia",
  "Lithuania", "Malaysia", "Malta", "Mexico", "Morocco", "Netherlands", "New Zealand", "Nigeria",
  "Norway", "Pakistan", "Panama", "Philippines", "Poland", "Portugal", "Qatar", "Romania",
  "Saudi Arabia", "Singapore", "South Africa", "South Korea", "Spain", "Sri Lanka", "Sweden",
  "Switzerland", "Thailand", "Turkey", "United Arab Emirates", "United Kingdom", "United States",
  "Vietnam",
];

export const QUALIFICATIONS = [
  "Master Unlimited",
  "Chief Officer Unlimited",
  "Officer of the Watch (OOW) Unlimited",
  "Chief Engineer Unlimited",
  "Second Engineer Unlimited",
  "Engineering Officer of the Watch (EOOW) Unlimited",
  "None held",
  "Relevant Maritime Degree",
  "Other",
];

export const VESSEL_TYPES = [
  "Bulk Carrier",
  "Car Carrier",
  "Container vessel",
  "Drill Ship",
  "FSRU - Floating Storage Regasification Unit",
  "General Cargo",
  "In-land watercraft (barges, etc)",
  "LNG",
  "LPG",
  "Nil",
  "Offshore",
  "Oil/Chemical Tanker",
  "Passenger",
  "Rigs",
  "Ro Ro",
  "Steam",
  "Yacht",
  "Other",
];

export const SHORESIDE_EXPERIENCE = [
  "Class surveyor/auditor",
  "DPA",
  "Dry dock supervision",
  "Flag surveyor/auditor",
  "Lecturer (Maritime)",
  "Load Master",
  "P&I Surveyor",
  "Pilot",
  "Technical Officer",
  "Technician",
  "Vessel Manager/Superintendent",
  "Other",
];

export const SURVEYING_EXPERIENCE = [
  "Bunker survey",
  "Cargo (dry bulk)",
  "Cargo (wet)",
  "Hatch cover, hold condition & cleanliness surveys",
  "Incident investigations",
  "ISM Audits",
  "Marine Coating Inspections",
  "M032 Inspection",
  "Navigation Audits",
  "On-hire / Off-hire Inspections",
  "P&I Club surveys",
  "Pre-PSC Inspection",
  "Pre-Vetting Inspection",
  "SIRE Inspections",
  "Structural damage survey",
  "Warranty survey",
  "Other",
];

export const VESSEL_TYPE_SURVEYING_EXPERIENCE = VESSEL_TYPES;

export const ACCREDITATIONS = [
  "CDI (Chemical Distribution Inst.)",
  "Chartered Engineer",
  "Class Society Trained",
  "Flag State",
  "FROSIO (coatings)",
  "IIMS",
  "IMCA (CMID Approved)",
  "Lloyd's Maritime Academy",
  "NACE (coatings)",
  "OVID",
  "Rightship",
  "SIRE",
  "Other",
];

export const COURSES_COMPLETED = [
  "Diploma in Marine Surveying",
  "DPA Course",
  "IFIA Certification",
  "ISM ISPS MLC Lead Auditor",
  "Marine Surveying Diploma",
  "Navigational Assessment",
  "RightShip (RSIQ) Training",
  "SIRE 2.0 Training",
  "Other",
];

export const emptyExperience = () => ({ years: "", months: "", days: "" });

export const initialConsultantRegistration = {
  firstName: "",
  lastName: "",
  phoneNumber: "",
  mobileNumber: "",
  nationality: "",
  employmentStatus: "",
  companyName: "",
  email: "",
  username: "",
  password: "",
  confirmPassword: "",
  dobDD: "",
  dobMM: "",
  dobYYYY: "",
  yearStarted: "",
  heardAbout: "",
  street1: "",
  street2: "",
  city: "",
  postalCode: "",
  country: "",
  stateRegion: "",
  discipline: "",
  rank: "",
  qualifications: [],
  qualifiedDD: "",
  qualifiedMM: "",
  qualifiedYYYY: "",
  experienceByQualification: {},
  vesselTypes: [],
  ports: [],
  shoresideExperience: [],
  surveyingExperience: [],
  vesselTypeSurveyingExperience: [],
  accreditations: [],
  coursesCompleted: [],
  references: [],
  photoFile: null,
  cvFile: null,
  inspectionCost: "",
  marketingConsent: false,
  disciplineOther: "",
  rankOther: "",
  qualificationsOther: "",
  vesselTypesOther: "",
  shoresideExperienceOther: "",
  surveyingExperienceOther: "",
  vesselTypeSurveyingExperienceOther: "",
  accreditationsOther: "",
  coursesCompletedOther: "",
};
