import { ArrowRight, Search, ShipWheel } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getInspectionWorkflows, initializeInspectionWorkflow } from "../api/inspectionWorkflowApi";
import { date, money } from "../components/workflow/stages/formatters";
import { WORKFLOW_STAGES } from "../components/workflow/workflowStages";
import "./InspectionWorkflow.css";

export default function InspectionWorkflowQueue(){const navigate=useNavigate();const [rows,setRows]=useState([]);const [filters,setFilters]=useState({search:"",stage:"all",status:"all"});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [opening,setOpening]=useState(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await getInspectionWorkflows(filters);setRows(response.data||[]);}catch(e){setError(e.response?.data?.message||"Unable to load inspection workflows.");}finally{setLoading(false);}},[filters]);useEffect(()=>{const id=setTimeout(load,250);return()=>clearTimeout(id);},[load]);
 const open=async(row)=>{setOpening(row.requestId);setError("");try{if(!row.workflowId)await initializeInspectionWorkflow(row.requestId);navigate(`/admin/inspection-workflow/${row.requestId}`);}catch(e){setError(e.response?.data?.message||"Unable to open this workflow.");setOpening(null);}};
 return <main className="workflow-page queue-page"><header className="workflow-page-head"><div className="workflow-title-mark"><ShipWheel size={21}/></div><div><h1>Inspection Workflow</h1><p>Manage inspections from quotation through payment closeout</p></div></header><section className="workflow-filters"><label className="workflow-search"><Search size={16}/><input aria-label="Search workflows" placeholder="Search request, vessel, client or port" value={filters.search} onChange={(e)=>setFilters({...filters,search:e.target.value})}/></label><label>Workflow stage<select value={filters.stage} onChange={(e)=>setFilters({...filters,stage:e.target.value})}><option value="all">All stages</option>{WORKFLOW_STAGES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Request status<select value={filters.status} onChange={(e)=>setFilters({...filters,status:e.target.value})}><option value="all">All statuses</option>{["open","pending","active","assigned","completed"].map(v=><option key={v}>{v}</option>)}</select></label></section>{error&&<div className="workflow-alert error">{error}</div>}<section className="workflow-table-shell"><table className="workflow-table"><thead><tr><th>Request</th><th>Vessel</th><th>Client</th><th>Service</th><th>Port</th><th>Required By</th><th>Approved Budget</th><th>Quotations</th><th>Workflow Stage</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{!loading&&rows.map(row=><tr key={row.requestId}><td data-label="Request"><strong>{row.reference}</strong><small>#{row.requestId}</small></td><td data-label="Vessel">{row.vesselName||"Not provided"}</td><td data-label="Client">{row.clientName||"Not provided"}</td><td data-label="Service">{row.service||"Not provided"}</td><td data-label="Port">{row.portName||"Not provided"}</td><td data-label="Required By">{date(row.requiredBy)}</td><td data-label="Approved Budget" className="money-cell">{money(row.approvedBudgetUsd)}</td><td data-label="Quotations">{row.quotationsAwaitingReview?`${row.quotationsAwaitingReview} awaiting review`:"No quotations"}</td><td data-label="Workflow Stage"><span className={`workflow-stage-chip ${row.currentStage==="invoice_paid"?"complete":""}`}>{row.currentStage==="invoice_paid"?"Complete":row.currentStage.replaceAll("_"," ")}</span></td><td><button className="row-action" disabled={opening===row.requestId} onClick={()=>open(row)}>Open Workflow <ArrowRight size={15}/></button></td></tr>)}</tbody></table>{loading&&<div className="workflow-loading">Loading approved requests…</div>}{!loading&&!rows.length&&!error&&<div className="workflow-empty"><h3>No approved requests found</h3><p>Try clearing the current filters.</p></div>}</section></main>}
