import pdfWorkerUrl from "pdfjs-dist/build/pdf.worker.min.mjs?url";
import { buildStructuredEvidence, clean, keyFor, normalizeLocalFields, suggestFieldsFromEvidence } from "./templateEvidence";

export { buildStructuredEvidence, mergeMappedFields, suggestFieldsFromEvidence, suggestFieldsFromText, usefulLocalFields } from "./templateEvidence";
export const SOURCE_LIMITS = { pdfBytes: 10 * 1024 * 1024, xmlBytes: 2 * 1024 * 1024, docxBytes: 10 * 1024 * 1024, xlsxBytes: 10 * 1024 * 1024, pdfPages: 25, ocrPages: 10, xlsxSheets: 10 };

function annotationField(annotation, pageNumber, index) {
  if (!annotation.fieldName || annotation.subtype !== "Widget") return null; const [x1, y1, x2, y2] = annotation.rect || []; const type = annotation.fieldType === "Btn" ? "checkbox" : annotation.fieldType === "Ch" ? "select" : "text";
  return { fieldKey: keyFor(annotation.fieldName, index), label: annotation.alternativeText || annotation.fieldName, type, defaultValue: annotation.fieldValue ?? "", options: type === "select" ? (annotation.options || []).map((option) => option.displayValue || option.exportValue) : [], sourceFieldName: annotation.fieldName, sourcePageNumber: pageNumber, sourceCoordinates: [x1, y1, x2, y2].every(Number.isFinite) ? { x: x1, y: y1, width: x2 - x1, height: y2 - y1 } : null, section: "Document fields" };
}

function pdfLines(items, styles = {}) {
  const rows = [];
  for (const item of items) {
    const text = clean(item?.str, 1000); if (!text) continue; const x = Number(item.transform?.[4]) || 0; const y = Number(item.transform?.[5]) || 0; const fontSize = Math.round(Math.hypot(Number(item.transform?.[0]) || 0, Number(item.transform?.[1]) || 0) * 10) / 10; const bold = /bold/i.test(`${item.fontName || ""} ${styles[item.fontName]?.fontFamily || ""}`);
    let row = rows.find((candidate) => Math.abs(candidate.y - y) <= 3); if (!row) { row = { y, items: [] }; rows.push(row); } row.items.push({ text, x, fontSize, bold });
  }
  return rows.sort((a, b) => b.y - a.y).map((row) => { const ordered = row.items.sort((a, b) => a.x - b.x); return { text: ordered.map((item) => item.text).join(" ").replace(/\s+/g, " ").trim(), x: ordered[0].x, y: row.y, fontSize: Math.max(...ordered.map((item) => item.fontSize)), bold: ordered.some((item) => item.bold) }; });
}

async function recognizeScannedPdf(pdf, signal, onProgress, onWorker) {
  if (pdf.numPages > SOURCE_LIMITS.ocrPages) throw new Error("This document exceeds the supported OCR page limit."); const { createWorker } = await import("tesseract.js"); let worker; const cancel = () => worker?.terminate(); signal?.addEventListener("abort", cancel, { once: true });
  try {
    onProgress?.({ stage: "Detecting text", percent: 20 }); worker = await createWorker("eng", undefined, { logger: (entry) => { if (entry.status === "recognizing text") onProgress?.({ stage: "Detecting text", percent: 20 + Math.round(entry.progress * 65) }); } }); onWorker?.(worker); const pages = [];
    for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber += 1) { if (signal?.aborted) throw new DOMException("Extraction cancelled.", "AbortError"); onProgress?.({ stage: `Reading page ${pageNumber} of ${pdf.numPages}`, percent: 20 + Math.round(pageNumber / pdf.numPages * 65) }); const page = await pdf.getPage(pageNumber); const viewport = page.getViewport({ scale: 1.5 }); const canvas = document.createElement("canvas"); canvas.width = Math.ceil(viewport.width); canvas.height = Math.ceil(viewport.height); const context = canvas.getContext("2d", { alpha: false }); await page.render({ canvasContext: context, viewport }).promise; const recognized = await worker.recognize(canvas); pages.push({ name: `Page ${pageNumber}`, lines: (recognized.data.text || "").split(/\r?\n/).map((text) => ({ text })) }); context.clearRect(0, 0, canvas.width, canvas.height); page.cleanup(); }
    onProgress?.({ stage: "Building field suggestions", percent: 95 }); const evidence = buildStructuredEvidence(pages); if (evidence.flatMap((page) => page.lines).map((line) => line.text).join("").replace(/\W/g, "").length < 20) throw new Error("OCR could not detect usable fields."); return { mode: "ocr", fields: suggestFieldsFromEvidence(evidence, "OCR suggestions"), pageCount: pdf.numPages, evidence: { pagesOrSheets: evidence }, aiMappingRecommended: true, message: "OCR field suggestions require review before saving." };
  } finally { signal?.removeEventListener("abort", cancel); await worker?.terminate(); onWorker?.(null); }
}

async function extractPdf(file, options) {
  options.onProgress?.({ stage: "Preparing document", percent: 5 }); const bytes = await file.arrayBuffer(); let loadingTask; let pdfDocument;
  try {
    const pdfjs = await import("pdfjs-dist/build/pdf.mjs"); pdfjs.GlobalWorkerOptions.workerSrc = pdfWorkerUrl; loadingTask = pdfjs.getDocument({ data: bytes }); pdfDocument = await loadingTask.promise; if (pdfDocument.numPages > SOURCE_LIMITS.pdfPages) throw new Error("This document exceeds the supported page limit."); const formFields = []; const pages = [];
    for (let pageNumber = 1; pageNumber <= pdfDocument.numPages; pageNumber += 1) { if (options.signal?.aborted) throw new DOMException("Extraction cancelled.", "AbortError"); options.onProgress?.({ stage: `Reading page ${pageNumber} of ${pdfDocument.numPages}`, percent: 10 + Math.round(pageNumber / pdfDocument.numPages * 55) }); const page = await pdfDocument.getPage(pageNumber); const annotations = await page.getAnnotations(); annotations.forEach((annotation) => { const field = annotationField(annotation, pageNumber, formFields.length); if (field) formFields.push(field); }); const content = await page.getTextContent(); pages.push({ name: `Page ${pageNumber}`, lines: pdfLines(content.items, content.styles) }); page.cleanup(); }
    for (const field of formFields) pages[field.sourcePageNumber - 1]?.lines.push({ text: field.label, x: field.sourceCoordinates?.x, y: field.sourceCoordinates?.y }); options.onProgress?.({ stage: "Building field suggestions", percent: 95 }); const evidence = buildStructuredEvidence(pages); const meaningful = evidence.flatMap((page) => page.lines).map((line) => line.text).join("").replace(/\W/g, "").length;
    if (formFields.length) return { mode: "acroform", fields: normalizeLocalFields(formFields), pageCount: pdfDocument.numPages, evidence: { pagesOrSheets: evidence }, aiMappingRecommended: false, message: "Fillable PDF fields were read locally. Review them before saving." };
    if (meaningful >= 20) return { mode: "text", fields: suggestFieldsFromEvidence(evidence), pageCount: pdfDocument.numPages, evidence: { pagesOrSheets: evidence }, aiMappingRecommended: true, message: "Cleaned PDF text is ready. Map fields with AI or edit the local suggestions." };
    return await recognizeScannedPdf(pdfDocument, options.signal, options.onProgress, options.onWorker);
  } catch (error) { if (error?.name === "PasswordException") throw new Error("This PDF is password protected.", { cause: error }); throw error; }
  finally { try { if (typeof pdfDocument?.cleanup === "function") await pdfDocument.cleanup(); if (typeof loadingTask?.destroy === "function") await loadingTask.destroy(); } catch (cleanupError) { console.warn("PDF resource cleanup:", cleanupError?.message || cleanupError); } }
}

function extractXml(fileText) {
  if (/<!DOCTYPE|<!ENTITY/i.test(fileText) || /<\?(?!xml(?:\s|\?>))/i.test(fileText)) throw new Error("This XML contains unsafe declarations or processing instructions."); const documentNode = new DOMParser().parseFromString(fileText, "application/xml"); if (documentNode.querySelector("parsererror")) throw new Error("Unable to parse this XML file.");
  const explicit = [...documentNode.querySelectorAll("inspectionTemplate section field")].map((node) => ({ fieldKey: node.getAttribute("fieldKey") || node.getAttribute("key"), label: node.getAttribute("label") || node.textContent.trim(), type: node.getAttribute("fieldType") || node.getAttribute("type") || "text", required: node.getAttribute("required") === "true", section: node.closest("section")?.getAttribute("title") || "General", defaultValue: node.getAttribute("defaultValue") || "" })); const generic = [...documentNode.querySelectorAll("*")].filter((node) => !node.children.length && node.textContent.trim()).map((node) => ({ label: node.localName.replace(/[_-]+/g, " "), type: "text", section: node.parentElement?.localName || "XML fields", defaultValue: node.textContent.trim(), suggested: true })); const fields = normalizeLocalFields(explicit.length ? explicit : generic); if (!fields.length) throw new Error("No supported field definitions were found in this XML file."); const evidence = buildStructuredEvidence([{ name: "XML", lines: [...documentNode.querySelectorAll("*")].filter((node) => !node.children.length && node.textContent.trim()).map((node) => ({ text: `${node.localName}: ${node.textContent.trim()}` })) }]); return { mode: explicit.length ? "nexaport_xml" : "generic_xml", fields, pageCount: null, evidence: { pagesOrSheets: evidence }, aiMappingRecommended: !explicit.length, message: explicit.length ? "NexaPort XML fields were read locally." : "XML text is ready for field mapping." };
}

async function extractDocx(file) { const mammoth = await import("mammoth/mammoth.browser"); const converted = await mammoth.convertToHtml({ arrayBuffer: await file.arrayBuffer() }); const documentNode = new DOMParser().parseFromString(converted.value, "text/html"); const evidence = buildStructuredEvidence([{ name: "Document", lines: [...documentNode.querySelectorAll("h1,h2,h3,h4,h5,h6,p,tr")].map((node) => ({ text: node.textContent, bold: /^H\d$/.test(node.tagName), fontSize: /^H\d$/.test(node.tagName) ? 16 : 12 })) }]); if (!evidence.length) throw new Error("No supported field definitions were found in this DOCX file."); return { mode: "text", fields: suggestFieldsFromEvidence(evidence, "DOCX suggestions"), pageCount: null, evidence: { pagesOrSheets: evidence }, aiMappingRecommended: true, message: "DOCX text is ready for field mapping." }; }

async function extractXlsx(file) {
  const { default: JSZip } = await import("jszip"); const zip = await JSZip.loadAsync(await file.arrayBuffer()); const parseXml = async (path) => { const entry = zip.file(path); return entry ? new DOMParser().parseFromString(await entry.async("text"), "application/xml") : null; }; const workbook = await parseXml("xl/workbook.xml"); const relationships = await parseXml("xl/_rels/workbook.xml.rels"); if (!workbook || !relationships) throw new Error("No supported field definitions were found in this XLSX file."); const relationPaths = new Map([...relationships.querySelectorAll("Relationship")].map((node) => [node.getAttribute("Id"), `xl/${node.getAttribute("Target").replace(/^\/?xl\//, "").replace(/^\.\.\//, "")}`])); const sheets = [...workbook.querySelectorAll("sheet")]; if (sheets.length > SOURCE_LIMITS.xlsxSheets) throw new Error("This workbook exceeds the supported worksheet limit."); const shared = await parseXml("xl/sharedStrings.xml"); const sharedStrings = shared ? [...shared.querySelectorAll("si")].map((node) => node.textContent) : []; const pages = [];
  for (const sheet of sheets) { const documentNode = await parseXml(relationPaths.get(sheet.getAttribute("r:id"))); const cellValues = new Map(); const rows = [...(documentNode?.querySelectorAll("row") || [])].map((row) => [...row.querySelectorAll("c")].map((cell) => { const type = cell.getAttribute("t"); const raw = type === "inlineStr" ? cell.querySelector("is")?.textContent : cell.querySelector("v")?.textContent; const value = type === "s" ? sharedStrings[Number(raw)] : raw; const text = clean(value, 500); if (text) cellValues.set(cell.getAttribute("r"), text); return text; }).filter(Boolean).join(" | ")).filter(Boolean); const merged = [...(documentNode?.querySelectorAll("mergeCell") || [])].map((node) => { const range = node.getAttribute("ref"); return `Merged heading ${range}: ${cellValues.get(range.split(":")[0]) || ""}`; }); pages.push({ name: clean(sheet.getAttribute("name"), 120), lines: [...merged, ...rows].map((text) => ({ text })) }); }
  const evidence = buildStructuredEvidence(pages); if (!evidence.length) throw new Error("No supported field definitions were found in this XLSX file."); return { mode: "text", fields: suggestFieldsFromEvidence(evidence, "XLSX suggestions"), pageCount: null, evidence: { pagesOrSheets: evidence }, aiMappingRecommended: true, message: "XLSX text is ready for field mapping." };
}

export async function extractTemplateSource(file, options = {}) { if (!file) throw new Error("Choose a PDF, XML, DOCX or XLSX file."); const extension = file.name.toLowerCase().split(".").pop(); if (extension === "pdf") return extractPdf(file, options); if (extension === "xml") { options.onProgress?.({ stage: "Preparing document", percent: 10 }); options.onProgress?.({ stage: "Building field suggestions", percent: 90 }); return extractXml(await file.text()); } if (extension === "docx") return extractDocx(file); if (extension === "xlsx") return extractXlsx(file); throw new Error("Choose a PDF, XML, DOCX or XLSX file."); }
