import { ShieldCheck } from "lucide-react";
import { DataRow, QuoteBreakdown } from "./StageData";
import { money } from "./formatters";

export default function StageConfirm({data,onConfirm,busy,adminMarkupUsd,setAdminMarkupUsd}) { const quote=data.selectedQuotation; if(!quote)return <section className="workflow-stage"><div className="workflow-empty"><h2>Quotation selection required</h2><p>Return to Quote and select an eligible Consultant quotation.</p></div></section>; const markup=Math.max(0,Number(adminMarkupUsd)||0); const final=quote.consultantTotalUsd+markup;
 return <section className="workflow-stage"><header className="stage-heading"><div><span>Stage 03</span><h2>Confirm quotation &amp; Surveyor</h2><p>This action accepts the quotation, rejects competing active quotes, and assigns its Consultant.</p></div></header><div className="stage-grid"><article className="workflow-panel"><h3>Request</h3><DataRow label="Vessel" value={data.request.vessel.name}/><DataRow label="Service" value={data.request.service}/><DataRow label="Approved request budget" value={money(data.request.approvedBudgetUsd)}/></article><article className="workflow-panel"><h3>Selected Consultant</h3><DataRow label="Name" value={quote.consultantName}/><DataRow label="Location" value={quote.consultantLocation}/><DataRow label="Rating" value={quote.consultantRating==null?"Not provided":`${quote.consultantRating} / 5`}/></article></div>
 <article className="workflow-panel confirmation-panel"><div><h3>Consultant quote</h3><QuoteBreakdown quote={quote}/></div><div className="markup-control"><label>Nexaport / Admin quotation fee (USD)<input type="number" min="0" step="0.01" value={adminMarkupUsd} onChange={(event)=>setAdminMarkupUsd(event.target.value)}/></label><div className="final-total"><span>Final client-facing total</span><strong>{money(final)}</strong><small>Approved request budget is reference-only and does not alter this calculation.</small></div></div></article>
 <footer className="stage-action-row"><span className="confirmation-note"><ShieldCheck size={17}/>Confirmation is transactional and cannot partially assign a Surveyor.</span><button className="workflow-primary" disabled={busy} onClick={()=>onConfirm(markup)}>{busy?"Confirming…":"Confirm Quotation & Assign Surveyor"}</button></footer></section>;
}
