import { CheckCircle2, Download, FileText } from "lucide-react";
import { useState } from "react";
import { DataRow } from "./StageData";
import { date, dateTime, money } from "./formatters";

const today=()=>new Date().toISOString().slice(0,10);

function CommercialLedger({accepted,invoice}){const invoiceAmount=invoice?.amountUsd;const variance=invoiceAmount==null||accepted==null?null:invoiceAmount-accepted;return <div className="commercial-ledger"><div><span>Accepted quotation</span><strong>{money(accepted)}</strong></div><div><span>Invoice amount</span><strong>{money(invoiceAmount)}</strong></div><div className={variance?"variance":""}><span>Variance</span><strong>{variance==null?"Not available":`${variance>0?"+":""}${money(variance)}`}</strong></div><div><span>Paid amount</span><strong>{money(invoice?.paidAmountUsd)}</strong></div></div>}

export default function StageInvoice({data,mode,busy,onSubmit,onApprove,onReject,onPay,onViewStage}){
  const invoice=data.invoice,accepted=data.acceptedQuotation?.clientTotalUsd??null,current=data.workflow.currentStage;
  const [form,setForm]=useState({invoiceNumber:invoice?.invoiceNumber||"",amountUsd:invoice?.amountUsd??accepted??"",currency:invoice?.currency||"USD",dueDate:invoice?.dueDate?.slice?.(0,10)||"",internalNote:invoice?.internalNote||"",file:null});
  const [rejectionReason,setRejectionReason]=useState("");
  const [payment,setPayment]=useState({paidAmountUsd:invoice?.amountUsd??"",paymentReference:"",paidDate:today(),paymentNotes:""});
  const variance=Number(form.amountUsd||0)-Number(accepted||0);
  const set=(name,value)=>setForm((state)=>({...state,[name]:value}));
  const setPaid=(name,value)=>setPayment((state)=>({...state,[name]:value}));
  const stageNumber=mode==="invoice_submitted"?11:mode==="invoice_approved"?12:13;
  const title=invoice?.status==="rejected"?"Invoice rejected":mode==="invoice_submitted"?"Invoice submitted":mode==="invoice_approved"?"Invoice approved":"Invoice paid";
  const canSubmit=mode==="invoice_submitted"&&((current==="inspection_completed"&&!invoice)||(current==="invoice_submitted"&&invoice?.status==="rejected"));
  const canApprove=mode==="invoice_approved"&&current==="invoice_submitted"&&invoice?.status==="submitted";
  const canPay=mode==="invoice_paid"&&current==="invoice_approved"&&invoice?.status==="approved";
  return <section className="workflow-stage invoice-stage"><header className="stage-heading"><div><span>Stage {String(stageNumber).padStart(2,"0")}</span><h2>{title}</h2><p>Record each financial milestone explicitly; quotation acceptance is not payment.</p></div>{current==="invoice_paid"&&<strong className="attention-pill active">Complete</strong>}</header><CommercialLedger accepted={accepted} invoice={invoice}/>{invoice?.status==="rejected"&&<div className="workflow-alert error" role="alert"><strong>Invoice rejected — correction required.</strong> {invoice.rejectionReason}<br/><small>Rejected {dateTime(invoice.rejectedAt)} by {invoice.rejectedBy?.name||"Super Admin"}.</small></div>}{canSubmit&&<><div className="stage-grid"><article className="workflow-panel invoice-form"><h3>{invoice?.status==="rejected"?"Correct invoice":"Invoice entry"}</h3><label>Invoice reference<input value={form.invoiceNumber} maxLength="80" onChange={(e)=>set("invoiceNumber",e.target.value)} placeholder="INV-2026-001"/></label><label>Invoice amount<input type="number" min="0.01" step="0.01" value={form.amountUsd} onChange={(e)=>set("amountUsd",e.target.value)}/></label><label>Currency<input value={form.currency} readOnly aria-label="Invoice currency"/></label><label>Due date <span>Optional</span><input type="date" value={form.dueDate} onChange={(e)=>set("dueDate",e.target.value)}/></label><label>Internal note <span>Optional</span><textarea rows="3" value={form.internalNote} onChange={(e)=>set("internalNote",e.target.value)}/></label></article><article className="workflow-panel invoice-document"><h3>Invoice document</h3><FileText size={22}/><p>Attach a private PDF if an invoice document is available.</p><label className="workflow-secondary">Choose PDF<input hidden type="file" accept="application/pdf" onChange={(e)=>set("file",e.target.files?.[0]||null)}/></label><span>{form.file?.name||(invoice?.hasInvoiceDocument?"Existing PDF retained":"No document selected")}</span>{accepted!=null&&Number(form.amountUsd)>0&&variance!==0&&<div className="invoice-variance">Invoice differs from the accepted quotation by <strong>{variance>0?"+":""}{money(variance)}</strong>.</div>}</article></div><footer className="stage-action-row"><span>{invoice?.status==="rejected"?"Resubmission returns the corrected invoice for approval.":"Submitting locks the invoice until it is rejected for correction."}</span><button className="workflow-primary" disabled={busy||!form.invoiceNumber.trim()||Number(form.amountUsd)<=0} onClick={()=>onSubmit(form)}>{invoice?.status==="rejected"?"Resubmit Invoice":"Submit Invoice"}</button></footer></>}
  {invoice&&!canSubmit&&<div className="stage-grid"><article className="workflow-panel"><h3>Invoice details</h3><DataRow label="Invoice reference" value={invoice.invoiceNumber}/><DataRow label="Amount / currency" value={`${money(invoice.amountUsd)} ${invoice.currency||"USD"}`}/><DataRow label="Submitted" value={dateTime(invoice.submittedAt)}/><DataRow label="Submitted by" value={invoice.submittedBy?.name}/><DataRow label="Submission" value={`#${invoice.submissionCount||1}`}/><DataRow label="Due date" value={date(invoice.dueDate)}/><DataRow label="Status" value={invoice.status}/><DataRow label="Notes" value={invoice.internalNote}/>{invoice.documentUrl&&<a className="workflow-secondary review-download" href={invoice.documentUrl} target="_blank" rel="noreferrer"><Download size={14}/> Open Invoice PDF</a>}</article><article className="workflow-panel"><h3>Lifecycle</h3><DataRow label="Approved" value={invoice.approvedAt?dateTime(invoice.approvedAt):null}/><DataRow label="Approved by" value={invoice.approvedBy?.name}/><DataRow label="Paid" value={invoice.paidAt?dateTime(invoice.paidAt):null}/><DataRow label="Paid by" value={invoice.paidBy?.name}/><DataRow label="Payment reference" value={invoice.paymentReference}/><DataRow label="Payment notes" value={invoice.paymentNotes}/></article></div>}
  {mode==="invoice_submitted"&&current==="invoice_submitted"&&invoice?.status==="submitted"&&<footer className="stage-action-row"><span>Invoice submitted. Review the locked values before approval.</span><button className="workflow-primary" onClick={()=>onViewStage("invoice_approved")}>Review for Approval</button></footer>}
  {mode==="invoice_approved"&&current==="invoice_submitted"&&invoice?.status==="rejected"&&<footer className="stage-action-row"><span>Approval is blocked until the invoice is corrected and resubmitted.</span><button className="workflow-primary" onClick={()=>onViewStage("invoice_submitted")}>Correct Invoice</button></footer>}
  {canApprove&&<><div className="confirmation-warning">Approval records the approving Super Admin. It does not record payment.</div><article className="workflow-panel invoice-form"><h3>Reject for correction</h3><label>Rejection reason<textarea rows="3" maxLength="2000" value={rejectionReason} onChange={(e)=>setRejectionReason(e.target.value)} placeholder="Explain what must be corrected before resubmission"/></label></article><footer className="stage-action-row"><button className="workflow-secondary" disabled={busy||!rejectionReason.trim()} onClick={()=>onReject({rejectionReason})}>Reject Invoice</button><button className="workflow-primary" disabled={busy} onClick={onApprove}>Approve Invoice</button></footer></>}
  {mode==="invoice_approved"&&current==="invoice_approved"&&<footer className="stage-action-row"><span>Invoice approved. Payment has not yet been received.</span><button className="workflow-primary" onClick={()=>onViewStage("invoice_paid")}>Record Payment</button></footer>}
  {canPay&&<><article className="workflow-panel payment-form"><h3>Payment record</h3><div><label>Paid amount (USD)<input type="number" min="0.01" step="0.01" value={payment.paidAmountUsd} onChange={(e)=>setPaid("paidAmountUsd",e.target.value)}/></label><label>Payment reference<input maxLength="120" value={payment.paymentReference} onChange={(e)=>setPaid("paymentReference",e.target.value)} placeholder="Bank or remittance reference"/></label><label>Payment date<input type="date" value={payment.paidDate} onChange={(e)=>setPaid("paidDate",e.target.value)}/></label><label>Payment notes <span>Optional</span><textarea rows="3" value={payment.paymentNotes} onChange={(e)=>setPaid("paymentNotes",e.target.value)}/></label></div></article><footer className="stage-action-row"><span>Recording payment closes this workflow.</span><button className="workflow-primary" disabled={busy||Number(payment.paidAmountUsd)<=0||!payment.paymentReference.trim()||!payment.paidDate} onClick={()=>onPay(payment)}>Record Payment</button></footer></>}
  {current==="invoice_paid"&&<div className="confirmation-success"><CheckCircle2 size={18}/><div><strong>Workflow Complete</strong><span>Payment was explicitly recorded. The invoice lifecycle is locked.</span></div></div>}</section>;
}
