import { Plus, Save, Trash2 } from "lucide-react";
import React from "react";
import { DataRow } from "./StageData";
import { date } from "./formatters";

const empty={classSurveyStatus:"",classificationSocietyOverride:"",master:{name:"",phone:"",email:""},shipEmail:"",crew:[],specialFocusAreas:[],owner:"",manager:"",charterer:"",portAgent:{name:"",company:"",phone:"",email:""},notes:""};
const Field=({label,value,onChange,readOnly,type="text"})=><label className="prep-field"><span>{label}</span><input type={type} value={value||""} readOnly={readOnly} onChange={(e)=>onChange(e.target.value)}/></label>;

export default function StagePreparation({data,onSave,onComplete,busy}){const locked=data.preparation.locked;const [form,setForm]=React.useState(()=>({...empty,...data.preparation.data,master:{...empty.master,...data.preparation.data?.master},portAgent:{...empty.portAgent,...data.preparation.data?.portAgent},crew:data.preparation.data?.crew||[],specialFocusAreas:data.preparation.data?.specialFocusAreas||[]}));const update=(key,value)=>setForm((current)=>({...current,[key]:value}));const updateNested=(group,key,value)=>setForm((current)=>({...current,[group]:{...current[group],[key]:value}}));const crew=(index,key,value)=>setForm((current)=>({...current,crew:current.crew.map((row,i)=>i===index?{...row,[key]:value}:row)}));const focus=(index,value)=>setForm((current)=>({...current,specialFocusAreas:current.specialFocusAreas.map((item,i)=>i===index?value:item)}));return <section className="workflow-stage"><header className="stage-heading"><div><span>Stage 05</span><h2>Inspection preparation</h2><p>Capture only operational details that are not already authoritative in the approved request.</p></div>{locked&&<strong className="attention-pill active">Final report locked</strong>}</header>
<article className="workflow-panel prep-summary"><h3>Inspection summary</h3><div className="prep-summary-grid"><DataRow label="Vessel" value={data.request.vessel.name}/><DataRow label="IMO" value={data.request.vessel.imoNumber}/><DataRow label="Type / flag" value={[data.request.vessel.type,data.request.vessel.flag].filter(Boolean).join(" · ")}/><DataRow label="Port" value={[data.request.port.name,data.request.port.country].filter(Boolean).join(", ")}/><DataRow label="Required date" value={date(data.request.requiredBy)}/><DataRow label="Client" value={data.client.name}/><DataRow label="Surveyor" value={data.surveyor?.name}/><DataRow label="Scope" value={data.request.scope}/></div></article>
<div className="prep-sections"><section><h3>Vessel &amp; class preparation</h3><div className="prep-grid"><Field label="Classification society override" value={form.classificationSocietyOverride} readOnly={locked} onChange={(v)=>update("classificationSocietyOverride",v)}/><Field label="Current class survey status" value={form.classSurveyStatus} readOnly={locked} onChange={(v)=>update("classSurveyStatus",v)}/></div></section><section><h3>Master &amp; ship contact</h3><div className="prep-grid"><Field label="Master name *" value={form.master.name} readOnly={locked} onChange={(v)=>updateNested("master","name",v)}/><Field label="Master phone" value={form.master.phone} readOnly={locked} onChange={(v)=>updateNested("master","phone",v)}/><Field label="Master email" type="email" value={form.master.email} readOnly={locked} onChange={(v)=>updateNested("master","email",v)}/><Field label="Ship email" type="email" value={form.shipEmail} readOnly={locked} onChange={(v)=>update("shipEmail",v)}/></div></section>
<section><div className="prep-section-head"><h3>Crew list</h3>{!locked&&<button className="workflow-secondary" type="button" onClick={()=>update("crew",[...form.crew,{name:"",position:"",nationality:"",experience:""}])}><Plus size={14}/> Add crew member</button>}</div><div className="crew-table"><div className="crew-head"><span>Name</span><span>Rank / position</span><span>Nationality</span><span>Relevant experience</span><span/></div>{form.crew.map((row,index)=><div className="crew-row" key={index}><input aria-label={`Crew ${index+1} name`} value={row.name} readOnly={locked} onChange={(e)=>crew(index,"name",e.target.value)}/><input aria-label={`Crew ${index+1} position`} value={row.position} readOnly={locked} onChange={(e)=>crew(index,"position",e.target.value)}/><input aria-label={`Crew ${index+1} nationality`} value={row.nationality} readOnly={locked} onChange={(e)=>crew(index,"nationality",e.target.value)}/><input aria-label={`Crew ${index+1} experience`} value={row.experience} readOnly={locked} onChange={(e)=>crew(index,"experience",e.target.value)}/>{!locked&&<button type="button" aria-label={`Remove crew member ${index+1}`} onClick={()=>update("crew",form.crew.filter((_,i)=>i!==index))}><Trash2 size={15}/></button>}</div>)}</div>{!form.crew.length&&<p className="prep-empty">No crew members added.</p>}</section>
<section><div className="prep-section-head"><h3>Special focus areas</h3>{!locked&&<button className="workflow-secondary" type="button" onClick={()=>update("specialFocusAreas",[...form.specialFocusAreas,""])}><Plus size={14}/> Add focus item</button>}</div><div className="focus-list">{form.specialFocusAreas.map((item,index)=><div key={index}><input value={item} readOnly={locked} onChange={(e)=>focus(index,e.target.value)} placeholder="Inspection-specific focus"/>{!locked&&<button type="button" onClick={()=>update("specialFocusAreas",form.specialFocusAreas.filter((_,i)=>i!==index))}><Trash2 size={15}/></button>}</div>)}</div></section>
<section><h3>Agent &amp; management</h3><div className="prep-grid"><Field label="Owner" value={form.owner} readOnly={locked} onChange={(v)=>update("owner",v)}/><Field label="Manager" value={form.manager} readOnly={locked} onChange={(v)=>update("manager",v)}/><Field label="Charterer" value={form.charterer} readOnly={locked} onChange={(v)=>update("charterer",v)}/><Field label="Port agent name" value={form.portAgent.name} readOnly={locked} onChange={(v)=>updateNested("portAgent","name",v)}/><Field label="Port agent company" value={form.portAgent.company} readOnly={locked} onChange={(v)=>updateNested("portAgent","company",v)}/><Field label="Port agent phone" value={form.portAgent.phone} readOnly={locked} onChange={(v)=>updateNested("portAgent","phone",v)}/><Field label="Port agent email" type="email" value={form.portAgent.email} readOnly={locked} onChange={(v)=>updateNested("portAgent","email",v)}/></div></section><section><h3>Additional notes</h3><textarea className="prep-notes" value={form.notes} readOnly={locked} onChange={(e)=>update("notes",e.target.value)} rows="5"/></section></div>{!locked&&<footer className="stage-action-row prep-actions"><button className="workflow-secondary" disabled={busy} onClick={()=>onSave(form)}><Save size={15}/> Save Draft</button>{data.workflow.currentStage==="preparation"&&<button className="workflow-primary" disabled={busy} onClick={()=>onComplete(form)}>Complete Preparation</button>}</footer>}</section>}
